config/routes.rb
Product::Application.routes.draw do
  get "product/create"

  post "product/create" =>"product#create", :as =>:create_product
  get "product/all" =>"product#all", :as =>:all_product
  get "product/new" =>"product#new", :as =>:new_product
  root :to => 'product#all'

   

end

app/models/product1.rb
class Product1 < ActiveRecord::Base
  attr_accessible :description, :name, :price
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def create
  end

  def new
    @product = Product1.new
  end

  def create
    puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#{params.inspect}"
    @product=Product1.new(params[:product])    
    puts "/n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1#{@product.inspect}"    
    respond_to do |format|
      @product.save
      format.html {redirect_to :all_product}
      format.json {rander :json => @product}
      format.xml {rander :xml => @product}
    end
  end

  def all
    @product=Product1.all
    puts"************************************Array : #{@product.inspect}"    
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Product</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product/all.html.erb
<h3>All Products</h3>
<br>
<%= link_to('Add New Product',{ :action => 'new'})%>
<br><br>
<table border="1">
  <tr><th>Name</th><th>Description</th><th>Price</th></tr>
<% @product.each do |i| %>
  <tr>
    <td><%=  i.name %></td>
    <td><%=  i.description %></td>
    <td><%=  i.price %></td>
  </tr>
<%end%>

</table>

app/views/product/create.html.erb
<h3>Product#create</h3>

app/views/product/new.html.erb
<h3>Product#new</h3>
<%= form_for @product , :as=> :product, :url=>create_product_path , :method=>'post' do |f| %>
<p>Product Name</p>
<%= f.text_field:name  %>
<p>Product Description</p>
<%= f.text_area:description, :rows=> '10',:columns =>'60' %>
<p>Product Price</p>
<%= f.text_field:price %><br/><br/>
<%= f.submit :submit %>
<% end %>